### ISSUE TITLE
[FEATURE] FailSafeMaxDuration option per cache level

### ISSUE THREAD

**Issue by RMcD** [ZiggyCreatures/FusionCache#105]
**Is your feature request related to a problem? Please describe.**
If you specify that you want a local memory cache `Duration` of 15 min and a `DistributedCacheDuration` of 5 hours, both of those values are overridden in the memory/Distributed Accessors when `IsFailSafeEnabled` is `true` with the `FailSafeMaxDuration` time when the CacheAccessors call: 
* [Distributed](https://github.com/ZiggyCreatures/FusionCache/blob/a7a173693ef48255c869fab74e2f3a15f9501320/src/ZiggyCreatures.FusionCache/FusionCacheEntryOptions.cs#L494)
* [Memory](https://github.com/ZiggyCreatures/FusionCache/blob/a7a173693ef48255c869fab74e2f3a15f9501320/src/ZiggyCreatures.FusionCache/FusionCacheEntryOptions.cs#L472)

The challenge is I want the local memory cache to have the short duration to avoid local memory pressure, but if I set `FailSafeMaxDuration` to 20 min, then the `DistributedCacheDuration` time on the distributed entries in the distributed cache themselves would think they don't 'logically expire' for 5 hours but the real world (Redis) cache implementation is going to expire those entries in 20min instead of 5 hours because that's what was passed to the IDistributedCache for options. It makes sense that the library would override the duration defaults with the `FailSafeMaxDuration` on the underlying providers to enable the expired but usable window needed for the Fail-safe behavior; but creates this gap where I'd like the `DistributedCacheDuration` to be significantly higher than the local memory cache values. Trying to set the `FailSafeMaxDuration` to 5 hours would result in the local entries staying in memory for that whole time unless the entry is a hit, at which time it would not be "valid" and replaced with another long storage duration but short intra-entry duration cache entry. 

**Describe the solution you'd like**
The `FailSafeMaxDuration` can stay the same.
A new `DistributedFailSafeMaxDuration` option is added to the `FusionCacheEntryOptions` that is used instead of `FailSafeMaxDuration` for the distributed cache when provided. Unit tests would be updated to include this scenario and ensure there aren't any rough edges around the cascading logic in the GetOrSet methods, etc.

**Describe alternatives you've considered**
I'm currently looking at working around this by disabling Fail-Safe altogether to enable the other split durations to be used. The downside with the configuration is losing the benefits of Fail Safe. e.g. Factory failure and distributed cache entry is just outside of valid, etc.

The other thought I'd has was to try and use adaptive caching to forcibly override the `FailSafeMaxDuration` for distributed cache calls with a value from a separate configuration source/value. My concern is that I'm not sure that covers all the scenarios, or how having variable entry durations would impact the Fail-Safe entry validity. Looking at it, it seems like the biggest issue is that at least sometimes, the same adaptive cache options are applied to both cache accessor calls.
i.e. If `Duration` is 15 min, `DistributedCacheDuration` is 5 hours `FailSafeMaxDuration` is set at 20min by default, but adaptively 5 hours on write from the factory, 30 min passes, the entry should be removed from the memory cache...

**Additional context**
If I missed a configuration option or alternative, please let me know! Thanks! Also, awesome cache library!

**Comment by RMcD** [comment]
I think I missread the actual provider cache calls. Going to look at that first.

**Comment by aKzenT** [comment]
@jodydonetti I'm currently experiencing the exact same issue. We have a large website with pages being cached in Redis. We only want to cache pages in memory for a short time to have less memory pressure, but with active fail safe this becomes impossible. In fact we don't really want/require a fail safe to protect us from Redis outtage since we depend on Redis in other ways and cannot handle a Redis outtage anyway.

**Comment by jodydonetti** [comment]
Hi all, I'll probably add this option in the next release.
I'm currently finishing the last touches on another feature, but after that I think I can add this fairly easily.


Will update soon.

**Comment by jodydonetti** [comment]
Hi @RMcD , sorry for not having answered before! I'll try to detail more tomorrow.

**Comment by aKzenT** [comment]
Is there an update on this? This is currently blocking us from using fail safes. If there is any chance to get this into the next release, it would be awesome!

**Comment by jodydonetti** [comment]
Hi @aKzenT and @RMcD , since the [named caches](https://github.com/ZiggyCreatures/FusionCache/issues/104) and [builder pattern](https://github.com/ZiggyCreatures/FusionCache/issues/106) features are taking some time to be in the right shape for a release, I'm thinking about pushing a new version quickly with this feature, probably this weekend.

Will update soon, hope this helps.

**Comment by aKzenT** [comment]
Thanks! That is much appreciated!

**Comment by jodydonetti** [comment]
Hi all, I've just pushed some commits in the main branch, with:
- the new `DistributedCacheFailSafeMaxDuration` [option](https://github.com/ZiggyCreatures/FusionCache/blob/f6dab864ce458682588045edb6ed326520d245f7/src/ZiggyCreatures.FusionCache/FusionCacheEntryOptions.cs#L158)
- a useful `SetDistributedCacheFailSafeOptions(...)` [method](https://github.com/ZiggyCreatures/FusionCache/blob/f6dab864ce458682588045edb6ed326520d245f7/src/ZiggyCreatures.FusionCache/FusionCacheEntryOptions.cs#L381) to set the new option (and possibly others in the future) in the usual fluent style
- some [tests](https://github.com/ZiggyCreatures/FusionCache/blob/f6dab864ce458682588045edb6ed326520d245f7/tests/ZiggyCreatures.FusionCache.Tests/MultiLevelTests.cs#L616) to cover the new behaviour

I will be pushing a new release with this + some other features in the weekend.

**Comment by jodydonetti** [comment]
The new [v0.19.0](https://github.com/ZiggyCreatures/FusionCache/releases/tag/v0.19.0) has been released, which includes this 🎉
