### ISSUE TITLE
[BUG] Disposed object access issue in the background

### ISSUE THREAD

**Issue by akoken** [ZiggyCreatures/FusionCache#119]
Hi @jodydonetti 

Thank you for all of your hard work on this project. I started exploring this wonderful library and came across an issue. I wanted to experiment with the factory timeout functionality and add a delay to my factory method. Everything was OK until the time-out factory threw the exception as below.

![image](https://user-images.githubusercontent.com/2880254/220860671-692ec126-032d-4aff-a6c0-a378dcae99d2.png)

Does FusionCache needs singleton DbContext? Or am I missing something?

**Configuration:**
```csharp
builder.Services.AddStackExchangeRedisCache(options =>
        {
            options.Configuration = redisConnectionString;
        });

        builder.Services.AddFusionCacheSystemTextJsonSerializer();

        builder.Services.AddFusionCacheStackExchangeRedisBackplane(options =>
        {
            options.Configuration = redisConnectionString;
        });

        builder.Services.AddFusionCache(options =>
        {
            options.DefaultEntryOptions = new FusionCacheEntryOptions
            {
                Duration = TimeSpan.FromMinutes(1),

                IsFailSafeEnabled = true,
                FailSafeMaxDuration = TimeSpan.FromMinutes(10),
                FailSafeThrottleDuration = TimeSpan.FromSeconds(30),

                FactorySoftTimeout = TimeSpan.FromMilliseconds(100),
                FactoryHardTimeout = TimeSpan.FromMilliseconds(1500),
                AllowBackgroundDistributedCacheOperations = true,
            };
        });
```

**Cache Entry:**
```csharp
await _fusionCache.GetOrSetAsync(
          $"Applications",
          async _ => await _applicationService.GetApplicationsAsync(cancellationToken),
          options =>
          options.SetDuration(TimeSpan.FromHours(1))
                 .SetDistributedCacheDuration(TimeSpan.FromDays(1))
                 .SetFailSafe(isEnabled: true, maxDuration: TimeSpan.FromDays(7), throttleDuration: TimeSpan.FromHours(1))
                 .SetFactoryTimeouts(softTimeout: TimeSpan.FromMilliseconds(300))
                 .SetDistributedCacheTimeouts(softTimeout: TimeSpan.FromMilliseconds(500)),
          token: cancellationToken);
```

**Factory:**
```csharp
 public async Task<List<ApplicationViewModel>> GetApplicationsAsync(CancellationToken cancellationToken)
    {
        await Task.Delay(5000);

        return await _unitOfWork.Repository<Application>().TableNoTracking
            .Select(x => new ApplicationViewModel(x.Id, x.Name))
            .ToListAsync(cancellationToken);
    }
```

I also attached detailed log.
[fusion-logs.txt](https://github.com/ZiggyCreatures/FusionCache/files/10811980/fusion-logs.txt)

**Versions**
I've encountered this issue on:
- FusionCache 0.19.0
- .NET 7
- Windows 10 x64

**Comment by jodydonetti** [comment]
Hi @akoken , and thanks for considering FusionCache!

Regarding the EF integration you are right, basically it's a problem of differences in the _lifetimes of various components_ (in this case, the `DbContext`).
Try to take a look at this [old issue](https://github.com/ZiggyCreatures/FusionCache/issues/21) to have an idea about the details and the suggest solution, which seemed to work fine.

Hope this helps, let me know!

**Comment by akoken** [comment]
Thanks for the quick reply @jodydonetti. TBH, I was also thinking about this solution as well since we currently use it in our background services :) I changed my factory method like below and it worked like a charm. The problem is that this solution is not recommended since it's a Service Locator anti-pattern. Event if I use, it will probably be rejected in the code review. I believe there isn't any better solution to this but to use ScopeFactory if I want to use factory timeout feature. In the light of this information, closing this issue. Thank you again!

```csharp
        await Task.Delay(5_000);

        using var scope = _scopeFactory.CreateScope();
        using var uow = scope.ServiceProvider.GetRequiredService<IUnitOfWork>();
        return await uow.Repository<Application>().TableNoTracking
            .Select(x => new ApplicationViewModel(x.Id, x.Name))
            .ToListAsync(cancellationToken);
```

**Comment by jodydonetti** [comment]
> I changed my factory method like below and it worked like a charm.

Awesome 🎉

> The problem is that this solution is not recommended since it's a Service Locator anti-pattern. Event if I use, it will probably be rejected in the code review.

Understood, but as you say there's really not a better way to handle this, if one wants both EF and timeouts handling.
Honestly it doesn't feel that bad, given the results that can be gained, but we'll see how it goes for you 🙂

I'm thinking about getting in touch with the EF team, to see if there's something that can be done about this situation, which I think is quite common even outside of the usage with FusionCache (like you mentioned, background jobs & co).

Maybe they already have something I'm not aware of, or they may introduce a feature to handle this scenario, like delaying context disposal in some way. 

> Thank you again!

Thanks to you, let me know if you need anything else!

**Comment by skarpovru** [comment]
It works like a charm, thank you. 
Can this edge case be added to the documentation? This is quite a common scenario to use caching with the Entity Framework.

**Comment by jodydonetti** [comment]
Hi @skarpovru and thanks for using FusionCache!

Happy this solution worked well for you.

And yes, you are right, there should be a set of common scenarios covered in the docs: I'm planning them for the big v1.0 release coming soon 😉

**Comment by digital88** [comment]
For anyone from future who will get there: instead of injecting DbContext in your service where FusionCache is used, inject IServiceScopeFactory. Then resolve DBContext in FusionCache factory method like this:
```
await using var scope = _serviceScopeFactory.CreateAsyncScope();
var _dbContext = scope.ServiceProvider.GetRequiredService<MyDbContext>();
```
