### ISSUE TITLE
[BUG] Type cannot be inferred from GetOrSetAsync

### ISSUE THREAD

**Issue by celluj34** [ZiggyCreatures/FusionCache#144]
**Describe the bug**
Since updating to 0.21, types cannot be inferred from `GetOrSetAsync`.

**To Reproduce**
```csharp
var date = _cache.GetOrSetAsync("my date",
    async (context, token) =>
    {
        return DateTime.Now;
    });
```

**Expected behavior**
I expect the types to be inferred from the return type of the factory.

**Versions**
I've encountered this issue on:
- FusionCache version 0.21

**Screenshots**
![image](https://github.com/ZiggyCreatures/FusionCache/assets/10264021/b5f8b98f-2cd2-41ef-ae80-0ccd881a64fa)

**Additional context**
You can work around the issue by providing the type explicitly in the method call, like so:

```csharp
var date = _cache.GetOrSetAsync<DateTime>("my date",
    async (context, token) =>
    {
        return DateTime.Now;
    });
```

**Comment by jodydonetti** [comment]
Hi @celluj34 , yep it was in the [release notes](https://github.com/ZiggyCreatures/FusionCache/releases/tag/v0.21.0)

![image](https://github.com/ZiggyCreatures/FusionCache/assets/1010086/c0e4b9df-0446-444e-b6d3-1e5acd7bfb40)

Sadly there's nothing I can do, it seems to be a limitation of the current version of the compiler.

**Comment by celluj34** [comment]
Ah, I see. Sorry I did not read thoroughly enough, I was too excited to start using the conditional refresh feature! Thank you for setting me straight!

**Comment by jodydonetti** [comment]
> I was too excited to start using the conditional refresh feature!

I'm you were expecting it so much, if you like let me know how it went 😁

**Comment by celluj34** [comment]
Honestly it's so much nicer than what I had to do before. The previous flow was complicated and we had to store 3 values for each set of data. We wanted to keep our data for 1 hour, but check at a maximum of every 10 minutes for staleness.

The way you've built the new methods with the existing FailSafe logic is just _perfect_ for our use case.

**Comment by jodydonetti** [comment]
Hi @celluj34 , what can I say? Thanks for your words, they made my day 😊

I'm glad it ended up working well and that you are liking the way I designed it, it means a lot!
