### ISSUE TITLE
[BUG] NullFusionCache throws when setupAction is used

### ISSUE THREAD

**Issue by kelko** [ZiggyCreatures/FusionCache#168]
**Describe the bug**

NullFusionCache.CreateEntryOptions throws "NotImplementedException"

**To Reproduce**
```csharp
// variant 1
var cache1 = new NullFusionCache(new FusionCacheOptions());
var result1 = await cache1.GetOrSetAsync<bool>(
    "some-name",
    (ctx, ct) => Task.FromResult(true),
    options => options.SetDuration(TimeSpan.FromSeconds(1)));

// variant 2
var cache2 = new NullFusionCache(new FusionCacheOptions());
var result2 = await cache2.GetOrSetAsync<bool>(
    "some-name",
    ct => Task.FromResult(true),
    options => options.SetDuration(TimeSpan.FromSeconds(1)));
```

**Expected behavior**

`GetOrSetAsync` with provided `setupAction` passes the result from `factory` through the same way the version without `setupAction` does.

**Versions**
FusionCache: 0.23.0
.NET 6

**Comment by jodydonetti** [comment]
Hi @kelko , the thing is:

![image](https://github.com/ZiggyCreatures/FusionCache/assets/1010086/2bbdb82d-b569-4fd1-8d75-26da1189c3d7)

So yeah, what can I say? I'm dumb 😅

Sorry about that, I'll fix it in the next release.

**Comment by jodydonetti** [comment]
Hi all, the [v0.24.0-preview1](https://github.com/ZiggyCreatures/FusionCache/releases/tag/v0.24.0-preview1) pre-release is out now on Nuget 🎉

NOTE: remember to check the "include prerelease" checkbox in your IDE to see it!

**Comment by jodydonetti** [comment]
Hi @kelko , have you been able to try the new version with the fix?

Thanks!

**Comment by kelko** [comment]
Hey @jodydonetti 
Sorry for the delay. I checked the preview1 for 0.24.0 and can confirm, that my test now successfully work with the NullFusionCache

**Comment by jodydonetti** [comment]
Great, thanks!
