### ISSUE TITLE
RobiniaDocs API Explorer

### ISSUE THREAD

**Issue by NeuroXiq** [ZiggyCreatures/FusionCache#174]
Maybe You will be interested in hosting API Explorer online:

https://www.robiniadocs.com/d/ziggycreatures-fusioncache/api/ZiggyCreatures.Caching.Fusion.FusionCache.html

This is ready-to-go, so above link can be added to README for other people to see it.
Or using ready shields.io badge:

[![Static Badge](https://img.shields.io/badge/API%20Documentation-RobiniaDocs-43bc00?logo=readme&logoColor=white)](https://www.robiniadocs.com/d/ziggycreatures-fusioncache/api/ZiggyCreatures.Caching.Fusion.FusionCache.html)

```
[![Static Badge](https://img.shields.io/badge/API%20Documentation-RobiniaDocs-43bc00?logo=readme&logoColor=white)](https://www.robiniadocs.com/d/ziggycreatures-fusioncache/api/ZiggyCreatures.Caching.Fusion.FusionCache.html)
```

https://github.com/NeuroXiq/RobiniaDocs

Maybe You will find RobiniaDocs interesting or useful

Regards
NeuroXiq

**Comment by jodydonetti** [comment]
Hi, thanks but I feel the current docs have the right approach overall.
