### ISSUE TITLE
[QUESTION] Manually remove Redis entry and backplane updates

### ISSUE THREAD

**Issue by JarrodOsborne** [ZiggyCreatures/FusionCache#180]
Hi, I haven't tried replicating this scenario but my question is...

If I have a two tier cache:
- local memory
- distributed (via Redis)
with Redis configured as the backplane.

If I manually removed an item from Redis using the CLI, for example:
`DEL MyCacheKey`

Would the backplane pick up on this and remove the entry from my local memory? 
Not sure if the backplane only works if interacting through FusionCache or the Redis SDK, or would any update (a CLI interaction in this case) work.

Thanks

**Comment by jodydonetti** [comment]
Hi Jarrod and thanks for using FusionCache!

AS you have guessed FusionCache does not pick up all the possible changes happening in the Redis instance, but requires you to tell it directly.

Hope this helps.
