### ISSUE TITLE
[FEATURE] Disable receiving backplane notifications

### ISSUE THREAD

**Issue by celluj34** [ZiggyCreatures/FusionCache#188]
## Problem
I have a specific use-case where my data API reads and writes to the cache, and a separate events API that _only_ writes to the cache (to be specific, it only removes entries from the cache). I would like to improve performance by having my events API ignore backplane notifications. I still want them _sent_ from the events API, but never received.

We are using redis as the distributed cache and backplane system.

## Solution
Perhaps some other option in the DI setup, `ReceiveBackplaneNotifications`.

## Alternatives
The only alternative we have now is to have the events API maintain a 'normal' cache instance.

## Additional context
n/a

**Comment by jodydonetti** [comment]
Hi @celluj34 sorry for the delay in answering, but I've been quite busy working on the `v1.0` that will be released in a matter of weeks (I released the `preview1` last week, please take a look if you can!) and preparing for some shows.

Anyway: last week with the `preview1` release of the `v1.0` I declared a feature freeze, but you asked for this in December and after analyzing it I've found that, on top of adding a new option in the `FusionCacheOptions` type, it would've been a matter of just 1 extra check on [2 lines total](https://github.com/ZiggyCreatures/FusionCache/blob/762eec2bb39749cbe309e375bcfd3a6088bf8157/src/ZiggyCreatures.FusionCache/Internals/Backplane/BackplaneAccessor.cs#L192).

And so here it is, the very [last feature](https://github.com/ZiggyCreatures/FusionCache/issues/201) before going full `v1.0`.

Please let me know what you think, hope this helps.

**Comment by jodydonetti** [comment]
Hi @celluj34 , I just released [`preview2`](https://github.com/ZiggyCreatures/FusionCache/releases/tag/v1.0.0-preview2) 🥳

Please give it a try, thanks!

**Comment by jodydonetti** [comment]
Hi all, I've finally released [v1.0](https://github.com/ZiggyCreatures/FusionCache/releases/tag/v1.0.0) 🥳

Feels a little unreal tbh, but yep: v1.0 is out.
