### ISSUE TITLE
[QUESTION] Can you tell if the cache hit comes from Memory or Distributed?

### ISSUE THREAD

**Issue by JarrodOsborne** [ZiggyCreatures/FusionCache#194]
I have a multi-layer FusionCache set up (in-memory & Redis).

My issue is that objects retrieved from the memory store need to be immutable, so I will likely have to clone them upon retrieval.
However I don't want to clone if the hit comes from Redis as that would be pointless. Is there a way to determine if the cache item retrieved came from in-memory or distributed?

**Comment by jodydonetti** [comment]
Closing as there has not been a response.

**Comment by JarrodOsborne** [comment]
Hi @jodydonetti 
I ended up writing a wrapper around IMemoryCache which does a clone.

```
public bool TryGetValue(object key, out object value)
{
    var exists = _memoryCache.TryGetValue(key, out object innerValue);
    value = innerValue?.Clone();
    return exists;
}
```

The clone is just a JSON copy
```
public static T Clone<T>(this T source) where T : class
{
    return JsonConvert.DeserializeObject<T>(JsonConvert.SerializeObject(source, _settings), _settings);
}
```

**Comment by jodydonetti** [comment]
Hi @JarrodOsborne , oooh that is smart, I haven't thought about it!

Glad it worked out in the end.

**Comment by JarrodOsborne** [comment]
@jodydonetti Going back to the original question, would this feature be considered in the future? I understand it's a little niche, but now I'm at the stage where I'm logging the duration of my cache operations and it would be nice to know what layer I'm hitting.
Unless there's another way to achieve this that I don't know about?

**Comment by jodydonetti** [comment]
Hi @JarrodOsborne , I'm not _planning_ it right now, but I'm still _thinking_ about how it could be made without a major change in the api surface area.

Do you have any hints or ideas you'd like to share?

**Comment by jodydonetti** [comment]
Hi all, [auto cloning](https://github.com/ZiggyCreatures/FusionCache/issues/279) is coming in v1.3.0 which will be out... I think later today 😬

Will update later.

**Comment by jodydonetti** [comment]
Hi all, [v1.3.0](https://github.com/ZiggyCreatures/FusionCache/releases/tag/v1.3.0) is out 🥳
