### ISSUE TITLE
[FEATURE] Add a method for list all caches in IFusionCacheProvider (Ex: for dispose purposes)

### ISSUE THREAD

**Issue by viniciusvarzea** [ZiggyCreatures/FusionCache#206]
## Problem

I think that a method for list all caches will be very helpfull, in many applications we need to dispose some objects before the application ends. We need to manually dispose all caches (hardcoded), if we have a method to list the registered caches, we could iterate over it and dispose all caches.

## Solution

Create a method at interface 'IFusionCacheProvider', called 'GetAllCaches' or something like it.

**Comment by viniciusvarzea** [comment]
Hello @jodydonetti thank you for the further response. I was worried about the dispose of the cache instances. 

Thank you for the excellent project, you guys really rock.

**Comment by jodydonetti** [comment]
> Hello @jodydonetti thank you for the further response. I was worried about the dispose of the cache instances.

Good, so I'll close this!

> Thank you for the excellent project, you guys really rock.

Thanks, even though "us guys" it's just me 😅

![image](https://github.com/ZiggyCreatures/FusionCache/assets/1010086/d26f2cc0-3a67-4f1f-ba83-a664b840058a)
