### ISSUE TITLE
[FEATURE] Post factory executed event with possibility to change the cache settings before it be inserted in cache

### ISSUE THREAD

**Issue by viniciusvarzea** [ZiggyCreatures/FusionCache#209]
## Problem

I need to set the cache duration after the factory is executed (based on the result of the factory) but before the result from factory be inserted in the cache.

## Solution

Maybe accepts a action with the some context in method (GetOrSetAsync) as a parameter, that will be called after a factory runs but before the result of the factory be inserted in the cache.

**Comment by jodydonetti** [comment]
Hi @viniciusvarzea and thanks for using FusionCache!


What you are looking for is already implemented and is called [Adaptive Caching](https://github.com/ZiggyCreatures/FusionCache/blob/main/docs/AdaptiveCaching.md).

Hope this helps.

**Comment by jodydonetti** [comment]
Hi @viniciusvarzea , did it work?

**Comment by viniciusvarzea** [comment]
@jodydonetti you are the best! It works
