### ISSUE TITLE
[BUG] Value is stored for longer than FailSafeMaxDuration

### ISSUE THREAD

**Issue by F2** [ZiggyCreatures/FusionCache#212]
First of all, thank you for this library! 
The best .NET caching library out there. 👍

## Describe the bug
According to the [Options docs](https://github.com/ZiggyCreatures/FusionCache/blob/main/docs/Options.md), the field `FailSafeMaxDuration` is _the amount of time a cached entry will be available_ when using fail-safe.

This is also backed by the [FailSafe docs](https://github.com/ZiggyCreatures/FusionCache/blob/main/docs/FailSafe.md). That example describes a `Duration` of **5 minutes**, a `FailSafeMaxDuration` of **2 hours**, and a `FailSafeThrottleDuration` of **1 minute**, and concludes: 

> a total 2 hours is passed (FailSafeMaxDuration): the value is actually deleted from the cache, like, **for real**

However, using the same example with smaller durations (see below), it seems that **the cache is never deleted** when the factory consistently fails.

## To Reproduce
Here's a [MRE (Minimal Reproducible Example)](https://en.wikipedia.org/wiki/Minimal_reproducible_example) of the issue:
```csharp
using ZiggyCreatures.Caching.Fusion;

var cache = new FusionCache(new FusionCacheOptions());
var entryOptions = new FusionCacheEntryOptions
{
    Duration = TimeSpan.FromSeconds(5),
    IsFailSafeEnabled = true,
    FailSafeMaxDuration = TimeSpan.FromSeconds(10),
    FailSafeThrottleDuration = TimeSpan.FromSeconds(2),
};

await cache.SetAsync("key", "value", entryOptions);

for (var i = 0; i < 60; i++)
{
    var value = await cache.GetOrSetAsync<string>("key", _ => throw new Exception(), entryOptions);
    Console.WriteLine($"[{i}s] Got value: {value}");

    await Task.Delay(1000);
}
```

## Expected behavior
It should not be possible to get the value after 10 seconds. It should throw an exception.

## Actual behavior
It keeps getting the value for forever.
![image](https://github.com/ZiggyCreatures/FusionCache/assets/916098/5b6a71c9-1e5e-4573-80ae-82572901184e)

Note, setting `FailSafeThrottleDuration` to a super high value makes it behave slightly better. In my example, it would throw an exception after 15 seconds. Still, according to documentation, it should happen after 10 seconds. And besides, using a throttle is a good idea.

## Versions
I've encountered this issue on:
- FusionCache 1.0.0 and 0.26.0
- .NET 8
- Win 11

## Additional information

As an aside, in the [FailSafe docs](https://github.com/ZiggyCreatures/FusionCache/blob/main/docs/FailSafe.md) it says:
- `FailSafeMaxDuration`: how long a value should be kept around at most, after its _logical expiration_

That makes it sound like if `Duration` is **5 seconds** and `FailSafeMaxDuration` is **10 seconds**, the total time the value would be kept around is **5+10** seconds. But that's inconsistent with the rest of the docs, including some of [your answers](https://github.com/ZiggyCreatures/FusionCache/issues/115#issuecomment-1425478794), stating it will take the highest value of the two.

**Comment by jodydonetti** [comment]
Hi @F2 and thanks for using FusionCache.

Sorry for the delay but I was at the MVP Global Summit and was not able to look into this.
Anyway interesting, you seem to be right at first glance: now that I'm back I'll look into this asap and will let you know.

Thanks!

**Comment by jodydonetti** [comment]
I'm looking into this, will update soon.

**Comment by jodydonetti** [comment]
Update: ok I think I've found the culprit, working on the best way to make the change considering all the edge cases.

**Comment by jodydonetti** [comment]
Hi, I just release [v1.1.0](https://github.com/ZiggyCreatures/FusionCache/releases/tag/v1.1.0) 🥳

**Comment by F2** [comment]
@jodydonetti Thank you so much. I can confirm it works in my code. 🤩

**Comment by jodydonetti** [comment]
![image](https://github.com/ZiggyCreatures/FusionCache/assets/1010086/cf9d9485-bd07-428b-8223-8967a31f7b84)
