### ISSUE TITLE
best way to store FusionCacheEntryOptions in iConfiguration 

### ISSUE THREAD

**Issue by sabbadino** [ZiggyCreatures/FusionCache#214]
## Problem
Suppose I have an application with many different FusionCacheEntryOptions requirement for different type of items to be cached.
I need to store each of such different setting in IConfiguration 

it would be nice to reuse the FusionCacheEntryOptions but it is sealed 

## Solution
If FusionCacheEntryOptions  was not sealed i could do something like this 

```
public class MyFusionCacheEntryOptions : FusionCacheEntryOptions {
	// use FusionCacheEntryOptions inherited properties to be used as default in 
	//  builder.Services.AddFusionCache().WithDefaultEntryOptions(
	
	public List<MyFusionCacheEntryOptionsEntry> CustomCacheSettings { get; init; } = new();
}

public class MyFusionCacheEntryOptionsEntry : FusionCacheEntryOptions {
	  public string Name { get; init; } = "";
}


```
and then I coudl do something like this when i need such settings

 ```
 var option = _fusionCacheSettingConfig.CustomCacheSettings.**SingleOrDefault(c => c.Name == "cacheentrytype1");**
   var ret = await _fusionCache.GetOrSetAsync(location, async _ => 
 {
     return await _weatherDataSource.GetCurrentTime(location, throwEx);
 }, **option**);
 return
```

## Alternatives
Is there another declarative, IConfiguration based solution I ma not aware to manage a large set of FusionCacheEntryOptions values ?

**Comment by pbolduc** [comment]
I suspect the class is sealed for performance reasons.  There is nothing stopping you from doing something like this:

```cs
        var settings = new Dictionary<string, FusionCacheEntryOptions>();

        string[] names = ["Foo"];
        foreach (var name in names)
        {
            var section = builder.Configuration.GetSection(name);
            var options = new FusionCacheEntryOptions();
            section.Bind(options);

            settings.Add(name, options);
        }

        builder.Services.AddSingleton(settings);
```

Or you could just wrap the type instead of inheriting from it.

```cs
public class NamedFusionCacheEntryOptions
{
    public string Name { get; set; }
    public FusionCacheEntryOptions CacheEntryOptions { get; set; }
}
```

**Comment by sabbadino** [comment]
Oh yes, composition over inheritance.. it was actually quite a naive question :)

**Comment by jodydonetti** [comment]
Hi all, sorry for the delay.
Thanks @pbolduc for the hint!
@sabbadino did it work?
