### ISSUE TITLE
[FEATURE] Optimise dependencies by adding TFM

### ISSUE THREAD

**Issue by thompson-tomo** [ZiggyCreatures/FusionCache#230]
### Is your feature request related to a problem? Please describe.
I want to minimise dependencies in my project by utilising framework dependencies wherever possible

### Describe the solution you'd like
I want the package to not have an explicit dependency on System.Text.Json as it can be provided by the framework. At the same time other dependencies can be optimised when an additional TFM is added.

### Describe alternatives you've considered
Accept the additional dependency

**Comment by jodydonetti** [comment]
Hi @thompson-tomo , sorry I don't understand what you are asking.

Which package are you talking about? The main FusionCache package does not have a dependency on System.Text.Json, and the package that act as an adapter for that serializer must have a dependency on it, otherwise it would not work.

Can you be clearer please?

**Comment by thompson-tomo** [comment]
@jodydonetti to make it clearer i have simply submitted a PR for the changes #231

**Comment by jodydonetti** [comment]
Thanks @thompson-tomo , will look into it and let you know.

**Comment by jodydonetti** [comment]
God damn it if it generates a ton of warnings now 😅

![image](https://github.com/ZiggyCreatures/FusionCache/assets/1010086/11e80f55-0624-4b55-a07b-2b98cc3838ce)

**Comment by thompson-tomo** [comment]
To make it easier i have just suppressed the build warnings via https://github.com/ZiggyCreatures/FusionCache/pull/233

**Comment by akoken** [comment]
Why .NET Core 3.1 @thompson-tomo? It's out of [support](https://dotnet.microsoft.com/en-us/platform/support/policy/dotnet-core) and full of vulnerabilities. No need to mention API changes that could be problematic. I think you shouldn't support it @jodydonetti?

**Comment by thompson-tomo** [comment]
I am aware of net core 3.1 is out of support but some users still utilise it & that is the earliest framework which can provide the necessary library as part of the framework. If a user is developing for net 6 then they will get v6 of STJ.

**Comment by jodydonetti** [comment]
Hi all, I think I need a little bit more time to get to the bottom of this, consider all the angles and the best approach all around.

I'll release the next version and then I'll come back to this.

Will update.

**Comment by thompson-tomo** [comment]
Note from my side I have no problem bumping it net 6 or potentially adding it as an additional TFM.

**Comment by jodydonetti** [comment]
Hi all, [v1.3.0](https://github.com/ZiggyCreatures/FusionCache/releases/tag/v1.3.0) is out 🥳
