### ISSUE TITLE
[FEATURE] 🔺 Add .NET Aspire support

### ISSUE THREAD

**Issue by jodydonetti** [ZiggyCreatures/FusionCache#237]
## What's this .NET Aspire thing?

Microsoft is about to release [.NET Aspire](https://learn.microsoft.com/en-us/dotnet/aspire/get-started/aspire-overview), which is _"an opinionated, cloud ready stack for building observable, production ready, distributed applications"_.

The project is getting quite a good amount of traction, and the community is liking it, so I thought about looking into it to see if there was a space for a FusionCache integration/support of some sort.

## The First Steps

While taking a look at it, I saw [this](https://learn.microsoft.com/en-us/dotnet/aspire/get-started/aspire-overview):

```csharp
// Create a distributed application builder given the command line arguments.
var builder = DistributedApplication.CreateBuilder(args);

// Add a Redis server to the application.
var cache = builder.AddRedis("cache"); // OOH, ADD REDIS? NICE 😏

// Add the frontend project to the application and configure it to use the 
// Redis server, defined as a referenced dependency.
builder.AddProject<Projects.MyFrontend>("frontend")
       .WithReference(cache);
```

As soon as I saw that `AddRedis("cache")` I thought _"cool, I can see something like `AddFusionCache("cache")` there, too!"_.

But then I looked into Aspire components, what they are, how they works, and I understood that an Aspire component exists when there's a server resource to handle, connect to, etc and this is not what FusionCache does: FusionCache may _use_ such a thing, but _it is not_ such a thing.

So I installed the necessary Visual Studio (2022 Preview, not the standard one) components and templates and just started playing with it to see what the experience would be.

## It Works!

In no time I've been able to make it work, which I think is a testament to the team's effort in the overall design of the development experience.

Now, with just this little piece of code in the `AppHost` (the project where Aspire components are configured):

```csharp
var builder = DistributedApplication.CreateBuilder(args);

var cache = builder.AddRedis("cache");

var apiService = builder.AddProject<Projects.AspireApp1_ApiService>("apiservice")
	.WithReference(cache); // THE PART I ADDED

builder.AddProject<Projects.AspireApp1_Web>("webfrontend")
	 .WithExternalHttpEndpoints()
	 .WithReference(cache)
	 .WithReference(apiService);

builder.Build().Run();
```

and this little piece of code in the `ApiService` (the project that _uses_ some of those Aspire components):

```csharp
var builder = WebApplication.CreateBuilder(args);

// Add service defaults & Aspire components.
builder.AddServiceDefaults();

// Add services to the container.
builder.Services.AddProblemDetails();

// THE PART I ADDED - BEGIN
builder.AddRedisDistributedCache("cache");

builder.Services.AddFusionCache()
	.WithSerializer(new FusionCacheSystemTextJsonSerializer())
	.WithRegisteredDistributedCache();

builder.Services.AddOpenTelemetry()
	.WithTracing(builder =>
	{
		builder.AddFusionCacheInstrumentation(o =>
		{
			o.IncludeMemoryLevel = true;
		});
	}).WithMetrics(builder =>
	{
		builder.AddFusionCacheInstrumentation(o =>
		{
			o.IncludeMemoryLevel = true;
			o.IncludeDistributedLevel = true;
			o.IncludeBackplane = true;
		});
	});
// THE PART I ADDED - END

var app = builder.Build();
```

So yeah, [it all worked](https://twitter.com/jodydonetti/status/1783510551055720585) and I've been able to launch the thing and see the results in the Aspire dashboard:

**Traces**
![image](https://github.com/ZiggyCreatures/FusionCache/assets/1010086/d09fe828-66c3-42b7-87fc-d9a4d9da0e01)

**Metrics**
![image](https://github.com/ZiggyCreatures/FusionCache/assets/1010086/e83a6492-3ca0-4513-8749-b16153b92631)

Nice, really nice 😬

Ok so _it works_, but is it as _nice_ as it could be? Nah, it could be better.

## Development Experience

One of my personal mantra with FusionCache is that it should be easy to use and the overall development experience should be as adherent as possible to the classic _"it just works"_.

For example when I added support for OpenTelemetry I've been able to make it work and the setup was _doable_, but with some manual steps, referencing some public consts for the ActivitySource etc: by creating instead a specific [package](https://www.nuget.org/packages/ZiggyCreatures.FusionCache.OpenTelemetry/) I made it work seamlessly and with ease (or so I hope 😅).

I'd like to do the same here with Aspire, by adding native Aspire support.

But, as I've been asked [_"what does Aspire support mean though?"_](https://twitter.com/davidfowl/status/1786027323760021666), the answer is an additional package to ease the development experience for having FusionCache work _with_ Aspire components. An example can be having FusionCache using the Redis component as a 2nd level distributed cache or a backplane.

Does this make sense? Is it worth it?

I'm trying to find out, and I'll use this issue to explore it and get some community response.

## How can it work

As can be seen in the example above it already "works", by simply:
- registering an `IDistributedCache` in the DI contaienr via `builder.AddRedisDistributedCache("cache")` (an ext method in the specific Redis package for Aspire support)
- using the registered `IDistributedCache` in FusionCache, by taking it from the DI container via the `WithRegisteredDistributedCache()` standard builder method of FusionCache

Would it be possible to have an additional ext method on the FusionCache builder to make things smoother? If so, how?

For example note that there's also an `builder.AddKeyedRedisDistributedCache("cache")` for dealing with multiple **keyed** services: since FusionCache already natively supports [multiple named caches](https://github.com/ZiggyCreatures/FusionCache/blob/main/docs/NamedCaches.md), that would work well together, right?

(I'll open another gh issue to explore adding support in FusionCache for keyed services, even though that has a different [set of problems](https://twitter.com/jodydonetti/status/1785708443640221696) to deal with).

Something I noticed is that Aspire-related ext methods are not tied to the usual `IServiceCollection` but to the "uppermost" `IHostApplicationBuilder`: that gives ext methods access to the inner `IServiceCollection`, but also direct access to the `IConfigurationManager`, `IMetricsBuilder`, `IHostEnvironment` and so on.

So, should I add `IHostApplicationBuilder`-based ext methods? Should it work with the existing `IServiceCollection`-based builder or replace it (I'd go with the former).

Another thing I'd like to smooth out is the observability setup, basically this part:

```csharp
builder.Services.AddOpenTelemetry()
	.WithTracing(builder =>
	{
		builder.AddFusionCacheInstrumentation(o =>
		{
			o.IncludeMemoryLevel = true;
		});
	}).WithMetrics(builder =>
	{
		builder.AddFusionCacheInstrumentation(o =>
		{
			o.IncludeMemoryLevel = true;
			o.IncludeDistributedLevel = true;
			o.IncludeBackplane = true;
		});
	});
```

For example, when registering the Redis IDistributedCache we saw above, instead of just saying `builder.AddRedisDistributedCache("cache")` we could go a step further and use:

```csharp
builder.AddRedisDistributedCache(
	"cache",
	settings =>
	{
		settings.Tracing = true;
		settings.HealthChecks = true;
	}
);
```

So in the same vein I can see something like:

```csharp
builder.AddFusionCache(
	"cache",
	settings =>
	{
		settings.Tracing = true;
		settings.Metrics = true;
		settings.HealthChecks = true; // NOTE: SHOULD FUSIONCACHE HAVE ALSO HEALTHCHECKS?
	}
);
```

And so on.

## I'd Like To Know

So I'd like to use this issue to gather ideas, suggestions and more to see first IF it makes sense to have a dedicated package to smooth out the developer experience for having FusionCache work with Aspire (I think so), and in that case how.

Any suggestion would be greatly appreciated, thanks!

**Comment by davidfowl** [comment]
cc @eerhardt

**Comment by jodydonetti** [comment]
Hi @celluj34 and thanks for chipping in.
Apart for an hypothetical more "native feeling" ext method, did the code above work well? Are you missing something?

**Comment by jodydonetti** [comment]
Closing this for now since:
- the current experience with FusionCache + Aspire is already working very well without extra efforts
- nobody has been able to come up with something Aspire-specific to do

Will re-open in the future if something new comes up.
