### ISSUE TITLE
[FEATURE] ⚡ Add `PreferSyncSerialization` option

### ISSUE THREAD

**Issue by jodydonetti** [ZiggyCreatures/FusionCache#245]
## Problem
Not really a problem, but it has been observed that in some situations async serialization and deserialization can be slower than the sync counterpart: this has nothing to do with FusionCache itself, but how serialization works in general.

It would be nice to allow users to specify a preference.

## Solution
Add a new option called `PreferSyncSerialization`, that can allow the sync version to be preferred.

The default would be `false` for full backward compatibility.

**Comment by jodydonetti** [comment]
Hi all, I just released [v1.2.0-preview1](https://github.com/ZiggyCreatures/FusionCache/releases/tag/v1.2.0-preview1) 🥳

**Comment by viniciusvarzea** [comment]
Hello @jodydonetti, yeah, since async serialization/deserialization works well with streams comming from io tasks (network streams, file streams etc), for memory streams the sync versions works alittle better. The adittion of this parameter will help us to have a better performance.
