### ISSUE TITLE
[FEATURE] Allow the factory to determine the cache duration?

### ISSUE THREAD

**Issue by onionhammer** [ZiggyCreatures/FusionCache#252]
## Problem
Often times the factory will tell you how long something should be cached for, but unless I'm not seeing it/it's not obvious, I don't believe FusionCache provides a way (like built in MemoryCache) to set an expiration within the factory method.

Example:
```C#
var authToken = await cache.GetOrSetAsync("MyCachedToken", async ct =>
{
    var context = new TokenRequestContext([...]);
    var response = await tokenCredential.GetTokenAsync(context, ct);
   
    // expiration is in the `response.ExpiresOn`
}, options => option.SetDurationMs(300) /* ExpiresOn inaccessible here */);
```

## Solution
Add a second overload to "GetOrSetAsync" and others which provides a second parameter to the cancellation token which lets the factory set the expiration

i.e.
```C#
var authToken = await cache.GetOrSetAsync("MyCachedToken", async (entry, cancellationToken) =>
{
    var context  = new TokenRequestContext([...]);
    var response = await tokenCredential.GetTokenAsync(context, cancellationToken);

    entry.AbsoluteExpiration = response.ExpiresOn - TimeSpan.FromSeconds(60);

    return response.Token;
}, static options => options
    // .SetDuration(TimeSpan.FromSeconds(30))
    .SetSkipDistributedCache(skip: true, skipBackplaneNotifications: true)
);
```

## Alternatives
Use IMemoryCache instead

**Comment by onionhammer** [comment]
Update: Ok, actually I think I found it?

```
// Add the Azure Maps token to the request
var authToken = await cache.GetOrSetAsync<string>("MyCachedToken", async (ctx, cancellationToken) =>
{
    var context  = new TokenRequestContext([...]);
    var response = await tokenCredential.GetTokenAsync(context, cancellationToken);

    ctx.Options.SetDuration(response.ExpiresOn - DateTimeOffset.UtcNow - TimeSpan.FromSeconds(60));

    return response.Token;
}, static options => options
    .SetDuration(TimeSpan.FromSeconds(30))
    .SetSkipDistributedCache(skip: true, skipBackplaneNotifications: true)
);
```

**Comment by jodydonetti** [comment]
Hi @onionhammer , yes I called it [Adaptive Caching](https://github.com/ZiggyCreatures/FusionCache/blob/main/docs/AdaptiveCaching.md), and you can change most of the entry options inside the factory to _adapt_ them to the factory result.

While we're here a tangential feature you may be interested in is [Conditional Refresh](https://github.com/ZiggyCreatures/FusionCache/blob/main/docs/ConditionalRefresh.md).

Hope this helps!

**Comment by onionhammer** [comment]
Thank you! I love the thorough documentation, I should really dedicate some time to it ha

**Comment by jodydonetti** [comment]
Thanks, I really appreciate it 😊
