### ISSUE TITLE
[QUESTION] best way to do unit testing of code using fusion cache 

### ISSUE THREAD

**Issue by sabbadino** [ZiggyCreatures/FusionCache#257]
hi , have you got some guidance about how to do unit testing of code that uses fusion cache ?
thanks 
P.S. : i use Moq in C#

**Comment by jodydonetti** [comment]
Hi @sabbadino , this has come up some time ago already, take a look [here](https://github.com/ZiggyCreatures/FusionCache/issues/31) and let me know if it helped.

**Comment by sabbadino** [comment]
oh yes i see .. I added a comment in that issue

**Comment by jodydonetti** [comment]
Saw it, thanks!

So should I close this?

**Comment by sabbadino** [comment]
Yes :)
