### ISSUE TITLE
[BUG] Adaptive Options Should Be Respected on Error

### ISSUE THREAD

**Issue by cmeyertons** [ZiggyCreatures/FusionCache#277]
## Describe the bug
Currently, adaptive options are not respected on an exception.  

This prevents application code from performing dynamic fail-safe logic based on the exception that was thrown  (#275 )

## To Reproduce
I have provided a PR with tests that were broken until illustrating the behavior (#276)

## Expected behavior
Adaptive options are now respected on error, allowing for dynamic fail-safe enablement

## Versions
I've encountered this issue on:
- FusionCache version: 1.2
- .NET version: net8.0
- OS version: Windows 10
- others: in-mem

**Comment by jodydonetti** [comment]
Hi @cmeyertons , thanks for pointing out this edge case.
I just reviewed + merged your PR, thanks a lot!

**Comment by jodydonetti** [comment]
Hi all, [v1.3.0](https://github.com/ZiggyCreatures/FusionCache/releases/tag/v1.3.0) is out 🥳
