### ISSUE TITLE
[BUG] GetOrSetAsync is not handling concurrent operations/threads

### ISSUE THREAD

**Issue by oasaleh** [ZiggyCreatures/FusionCache#281]
## Describe the bug
I'm calling a method from multiple threads. This method gets the cache and then looks in it for a value (the same value for all the threads.) Even though `tokenCacheKey` and `acquireTokenFunc` passed are the same for all the threads, the factory function (the 2nd param for `GetOrSetAsync`) is being called for every thread.

## To Reproduce
```c#
    private async Task<string> GetTokenInternalAsync(string tokenCacheKey,
        Func<Task<AuthenticationResult>> acquireTokenFunc)
    {
        IFusionCache cache = cacheProvider.GetCache(Constants.TokenCacheName);
        bool fromCache = true;
        TimeSpan expirationDuration = TimeSpan.FromDays(1); // To avoid compiler complaining of unassigned variable

        // Try to get the token from the cache
        string token = await cache.GetOrSetAsync(
            tokenCacheKey,
            async _ =>
            {
                logger.LogInformation("{token} not found in cache. Acquiring a new token.", tokenCacheKey);
                // If the token is not in the cache, acquire a new one
                AuthenticationResult result = await acquireTokenFunc();
                // Calculate the expiration duration based on the token's ExpiresOn property
                expirationDuration = result.ExpiresOn - DateTime.UtcNow;

                logger.LogInformation($"New token acquired. Expiration duration set to {expirationDuration}.");

                fromCache = false;
                return result.AccessToken;
            },
            options => options.SetDuration(expirationDuration)
        );

        if (fromCache)
        {
            logger.LogInformation("{token} retrieved from cache.", tokenCacheKey);
        }

        return token;
    }
```

## Expected behavior
For the same `tokenCacheKey`, the constructor should have only been invoked once (and accordingly, `acquireTokenFunc()` should have been invoked once as well.)

## Versions
I've encountered this issue on:
- FusionCache version 1.2.0
- .NET version 8
- OS version Windows 11

**Comment by jodydonetti** [comment]
Hi @oasaleh , I'll look into this, but can you give me your DefaultEntryOptions setup please?

**Comment by oasaleh** [comment]
@jodydonetti, thank you. Here's my setup in *Startup.cs*.

```c#
        services.AddFusionCache(Constants.TokenCacheName).WithDefaultEntryOptions(opt =>
        {
            opt.Duration = TimeSpan.MaxValue;
        });
```

**Comment by oasaleh** [comment]
I found the problem.
I can't do this *inside* the method: `IFusionCache cache = cacheProvider.GetCache(Constants.TokenCacheName);`. It must be done in the constructor instead. Now it's working!

**Comment by jodydonetti** [comment]
I'm glad it works now!

One thing though, to avoid surprising for you.
In your factory you are doing:

```csharp
// Calculate the expiration duration based on the token's ExpiresOn property
expirationDuration = result.ExpiresOn - DateTime.UtcNow;
```

This does nothing, meaning it's just changing a variable declared outside.
If you want to do [adaptive caching](https://github.com/ZiggyCreatures/FusionCache/blob/main/docs/AdaptiveCaching.md) you need to change the context's options, like this:

```csharp
// Calculate the expiration duration based on the token's ExpiresOn property
ctx.Options.Duration = result.ExpiresOn - DateTime.UtcNow;
```

Hope this helps.

**Comment by oasaleh** [comment]
> This does nothing, meaning it's just changing a variable declared outside.

But I am using it in my options.
`options => options.SetDuration(expirationDuration)`
This is not being taken into account?

**Comment by jodydonetti** [comment]
Oh yeah absolutely it is, but when calling the `GetOrSet` method, not **after** the execution of the factory.

Let's try to clear up the flow:
- you call `GetOrSet`
- the method needs entry options, and you specified them with the `options => options` lambda
- FusionCache takes the `DefaultEntryOptions`, duplicate them, and apply the lambda you specified
- the resulting entry options are used
- internally, it checks the cache and sees that the cached data is not there (or is expired)
- so it calls the factory

So there's no way to change a variable used beore to affect options already calculated.
The way to change some options in the factory is via Adaptive Caching as I highlighted, byt using `ctx.Options.Duration = ...`.

Hope this helps!
