### ISSUE TITLE
[BUG] System.Net.Http.HttpRequestException: Response status code does not indicate success: 304 (Not Modified).

### ISSUE THREAD

**Issue by onionhammer** [ZiggyCreatures/FusionCache#283]
## Describe the bug
This appears to be a bug in the documentation, but if you follow this guide: https://github.com/ZiggyCreatures/FusionCache/blob/main/docs/ConditionalRefresh.md#-a-practical-example

Calling 'EnsureSuccessStatusCode' will fail if the server really does reply with 304 not modified, because that is not considered a "success code"

https://learn.microsoft.com/en-us/uwp/api/windows.web.http.httpresponsemessage.ensuresuccessstatuscode?view=winrt-26100#remarks

> If the server doesn't return a successful [HttpStatusCode](https://learn.microsoft.com/en-us/uwp/api/windows.web.http.httpstatuscode?view=winrt-26100) in the Successful range (200-299) for the request, then the [HttpResponseMessage.IsSuccessStatusCode](https://learn.microsoft.com/en-us/uwp/api/windows.web.http.httpresponsemessage.issuccessstatuscode) property is set to false. Calling EnsureSuccessStatusCode causes the value of IsSuccessStatusCode to be checked, and an exception thrown if that value is false. No exception is thrown if the value is true.

**Comment by jodydonetti** [comment]
Hi @onionhammer , good catch, thanks!

PR merged.
