### ISSUE TITLE
How I can sync data between cache and Database immeditately

### ISSUE THREAD

**Issue by Son81** [ZiggyCreatures/FusionCache#298]
Im using Fusion Cache, Could you please help me fix this use case, many thanks

This will not work.. use case
- You have data loaded in Vendor cache at Time - T1
- Use logged in and update data for Vendor V1 and Time - T2
- Record for V1 saved in Database
- record in Vendor cache for V1 should be updated in cache .
- Cache and Store (DB data should be in sync)

My code 

```csharp
 string strStart, strEnd = "";
 _stopwatch = new System.Diagnostics.Stopwatch();
 _stopwatch.Start();
 strStart = _stopwatch.ElapsedMilliseconds.ToString();
 bool isDb = false;
 try
 {
     List<T> results = null;
     results = _cache.GetOrSet<List<T>>(
        keyCache,
       (ctx, ct) =>
       {
           isDb = true;
           List<T> result = getMethod(param) as List<T>;


           _cache.Events.Memory.Eviction += (s, e) =>
           {
               RemoveCacheValue(keyCache);
               result = GetCacheValue<T>(keyCache) as List<T>;


               CheckLogTime.LogWrite(keyCache + " = ", strStart, strEnd, "Data in cache named " + e.Key.ToString() + "  had been expired and removed");
           };                     
         
           #region comment
           //if (resuls is null)
           //{
           // CACHE null FOR 5 minutes
           //ctx.Options.Duration = TimeSpan.FromMinutes(5);
           // }
           //_cache.SetAsync($"{SettingConfigCache.Prefix}" + nameCache, _vendorServices.GetVendorSummaryDataByFilter(request));
           #endregion

           _stopwatch.Stop();
           strEnd = _stopwatch.ElapsedMilliseconds.ToString();
           string info = String.Format("Get data from database {0} milliseconds and start at = {1}", _stopwatch.ElapsedMilliseconds.ToString(), DateTime.UtcNow.ToString("h:mm:ss:tt"));
           CheckLogTime.LogWrite(keyCache + " = ", strStart, strEnd, info);

           return result;
       });
     if (isDb == false)
     {
         strEnd = _stopwatch.ElapsedMilliseconds.ToString();
         CheckLogTime.LogWrite(keyCache + " = ", strStart, strEnd, "Get data from cache " + _stopwatch.Elapsed.TotalMilliseconds + " milliseconds and start at = " + DateTime.UtcNow.ToString("h:mm:ss:tt"));
     }
     return results;
```

thank you

**Comment by jodydonetti** [comment]
Hi @Son81 , I [reformatted](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks) your question for readability.

Will answer in a moment, I'm reading it.

**Comment by jodydonetti** [comment]
> This will not work.. use case
> 
> - You have data loaded in Vendor cache at Time - T1
> - Use logged in and update data for Vendor V1 and Time - T2
> - Record for V1 saved in Database
> - record in Vendor cache for V1 should be updated in cache .
> - Cache and Store (DB data should be in sync)

I'm not sure I understand, do you want to update the database and immediately the cache?

If so you can do this:

```csharp
void UpdateProduct(Product product) {
  // I DON'T KNOW WHAT DB OR ORM YOU ARE USING, THIS IS GENERIC CODE
  UpdateDatabase(updatedProduct);
  // UPDATE THE CACHE
 _cache.Set("product-key", product);
}
```

Basically when you update the database you also immediately update the cache, there's nothing magic that will do that for you.

Regarding your code sample: inside your factory (that will run every time data is not fresh in the cache) you are adding an event listener for the eviction (this `_cache.Events.Memory.Eviction += ...`).
This is wrong, since if you need to be notified you can register the event handler only once at the beginning, at setup time or similar.

I don't know what `RemoveCacheValue` and `GetCacheValue` do: I can imagine, but without the code I'm not sure _how_ they do it.

If you can give me more info I can try to help more.

**Comment by Son81** [comment]
Thanks for your support, let me following your idea

Regards
Son
________________________________
