### ISSUE TITLE
[FEATURE] Can MemeryPack supprot BrotliCompressor?

### ISSUE THREAD

**Issue by brotherhorse** [ZiggyCreatures/FusionCache#302]

**Comment by jodydonetti** [comment]
Hi @brotherhorse , yes MemoryPack supports Brotli compression, see [here](https://github.com/Cysharp/MemoryPack).

I think you can mark your classes with some attributes and it should work.

Hope this helps, let me know if it worked.

**Comment by brotherhorse** [comment]
How to set BrotliCompressor(var compress)?

MyCode:
    _fusionCache = new FusionCache(
    new FusionCacheOptions
    {
        DefaultEntryOptions = new FusionCacheEntryOptions(TimeSpan.FromSeconds(absoluteExpiration))
    });
    var compress = new BrotliCompressor();
    var options = new MemoryPackSerializerOptions();
    var serializer = new FusionCacheCysharpMemoryPackSerializer(options);
    //add DistributedCach           
    _fusionCache.SetupDistributedCache(ocs.DistributedCache, serializer);
    //add Backplane
    _fusionCache.SetupBackplane(ocs.Create(_channel));

**Comment by jodydonetti** [comment]
Yeah @brotherhors I saw it, but it was 2am here in Italy and I have a daily job.
Will get back to you as soon as I can.

**Comment by jodydonetti** [comment]
Btw, have you tried this:

> I think you can mark your classes with some attributes and it should work.

?

**Comment by jodydonetti** [comment]
Hi, I've had some time to look at this.
It seems like currently it's not possible to use the BrotliCompressor directly.

Separately I'm working on compression in general, not just Brotli for MemoryPack, but it will need some more time, so don't wait for it soon.

I may have a temporary solution for you, but I need a little bit more time.

**Comment by brotherhorse** [comment]
Sorry to disturb your rest. 
Thank you very much for your reply. As Redis requires compressed storage to save space, I can temporarily use CompressLZ4. 
Thank you again.

**Comment by jodydonetti** [comment]
> Sorry to disturb your rest.

No disturb at all!
It's just that I was not able to answer earlier 🙂

> Thank you very much for your reply. As Redis requires compressed storage to save space, I can temporarily use CompressLZ4. Thank you again.

You're welcome, I'll update you in the future when compression may become a native, full-fledged feature of FusionCache.

Best.

**Comment by aleroca96** [comment]
hi - first of all thanks for an amazing library!

I was wondering if there is any compression set up as default now, or do we need to add our own serialiser?

Many thanks in advance

**Comment by jodydonetti** [comment]
Hi @aleroca96 

> hi - first of all thanks for an amazing library!

Thanks, appreciate it!

> I was wondering if there is any compression set up as default now, or do we need to add our own serialiser?

Nope sorry, not yet available.
