### ISSUE TITLE
[FEATURE] Can factory return nullable item?

### ISSUE THREAD

**Issue by brotherhorse** [ZiggyCreatures/FusionCache#304]
## Problem
TItem is a class or record,OnCallBack must return a UNnullable TItem,but readObjectAsync return a nullable TItem, so I return **item!**. But I don't think this meets strict standards

Code:

```csharp
 var item2 = await _fusionCache.GetOrSetAsync<TItem>(realKey, OnCallBack);
 async  Task<TItem> OnCallBack(FusionCacheFactoryExecutionContext<TItem> context,CancellationToken token)
 {                   
      var item = await  readObjectAsync();
      if(item is null)
      {
          if(context.Options.Duration.Seconds>60)
              context.Options.Duration=TimeSpan.FromMinutes(1);
      }
      return item!;                    
  }
```

## Solution
factory return nullable TValue

```csharp
GetOrSetAsync<TValue>(this IFusionCache cache, string key, Func<CancellationToken, Task<TValue>> factory, FusionCacheEntryOptions? options = null, CancellationToken token = default)
```

==>

```csharp
GetOrSetAsync<TValue>(this IFusionCache cache, string key, Func<CancellationToken, Task<TValue?>> factory, FusionCacheEntryOptions? options = null, CancellationToken token = default)
```

**Comment by brotherhorse** [comment]
Code:

var item2 = await _fusionCache.GetOrSetAsync<TItem>(realKey, OnCallBack);
async Task OnCallBack<TItem>(FusionCacheFactoryExecutionContext <TItem> context,CancellationToken token)
{
var item = await readObjectAsync();
if(item is null)
{
if(context.Options.Duration.Seconds>60)
context.Options.Duration=TimeSpan.FromMinutes(1);
}
return item!;
}

**Comment by brotherhorse** [comment]
Why are generic types removed from the code after I submit the edited question

**Comment by Amberg** [comment]
> Why are generic types removed from the code after I submit the edited question
- Use The code formatting the "<>" symbol above. Then your request does not look so **ugly**
```
async Task OnCallBack<T>(FusionCacheFactoryExecutionContext context,CancellationToken token)
{
}
```

If I understand you correctly, you just want to return a nullable from you factory. GetOrSetAsync is generic and the type is in you example interfered from the callback.
To be sure you can explicitly set the type
ae
`await _fusionCache.GetOrSetAsync<double?>("key", OnCallBack)`

**Comment by jodydonetti** [comment]
> Why are generic types removed from the code after I submit the edited question

When you post some code, you need to enclose it in triple-backtick (the character ` ), like this:

```
var foo = "bar";
```

Otherwise the < character is interpreted as html, and will be processed.

Also, it is suggested to specify the language, like "```csharp"

Lokk [here](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks) for more info.

**Comment by jodydonetti** [comment]
Hi @brotherhorse 

> TItem is a class or record,OnCallBack must return a UNnullable TItem

Ok, so this is a constraint.

> but readObjectAsync return a nullable TItem, so I return **item!**.
> But I don't think this meets strict standards

In general I agree: if a method MUST NOT return `null` and it calls another method that CAN return `null`, you need to handle that case specifically: one way may be to use a default value of type TItem (non `null` of course), and return it instead of `null`.




> Code:
> 
> ```cs
>  var item2 = await _fusionCache.GetOrSetAsync<TItem>(realKey, OnCallBack);
>  async  Task<TItem> OnCallBack(FusionCacheFactoryExecutionContext<TItem> context,CancellationToken token)
>  {                   
>       var item = await  readObjectAsync();
>       if(item is null)
>       {
>           if(context.Options.Duration.Seconds>60)
>               context.Options.Duration=TimeSpan.FromMinutes(1);
>       }
>       return item!;                    
>   }
> ```
> 
> ## Solution
> factory return nullable TValue

I don't understand 2 things:
- previously you said that "OnCallBack must return a UNnullable TItem", can this requirement change?
- it looks to me FusionCache does not have anything to do with this, or am I missing something?

Help me understand more what is the problem related to FusionCache.

I don't know if this is what you are looking for, but you can use `TItem?` (nullable TItem) in the `GetOrSet` call, like this:

```csharp
var item2 = await _fusionCache.GetOrSetAsync<TItem?>(realKey, OnCallBack);
async  Task<TItem?> OnCallBack(FusionCacheFactoryExecutionContext<TItem?> context, CancellationToken token)
{                   
  var item = await  readObjectAsync();
  if (item is null)
  {
    if (context.Options.Duration.Seconds > 60)
      context.Options.Duration = TimeSpan.FromMinutes(1);
  }
  return item;
}
```

Is this what you meant?

**Comment by jodydonetti** [comment]
Oh, also: there's a bug in your code that checks for the current cache duration, specifically here:

```csharp
...

if (context.Options.Duration.Seconds > 60)
  context.Options.Duration = TimeSpan.FromMinutes(1);

...
```

In the code above `Duration.Seconds` gives you the _"seconds component of the time interval"_ (see [here](https://learn.microsoft.com/en-us/dotnet/api/system.timespan.seconds?view=net-8.0)).

This is NOT the same as getting the whole TimeSpan itself expressed in seconds, for which you have to use `TimeSpan.TotalSeconds` (see [here](https://learn.microsoft.com/en-us/dotnet/api/system.timespan.totalseconds?view=net-8.0)).

For example if you have a `TimeSpan` with a value of `10 min and 20 sec`:
- with `TimeSpan.Seconds` you'll get `20`
- with `TimeSpan.TotalSeconds` you'll get `620`

Hope this helps!

**Comment by brotherhorse** [comment]
> * TotalSeconds

Yes,it is a mistake,it should be TotalSeconds

**Comment by brotherhorse** [comment]
What I mean is this:
```csharp
await _fusionCache.GetOrSetAsync<TItem?>(realKey, OnCallBack)
async Task<TItem?> OnCallBack(FusionCacheFactoryExecutionContext<TItem?> context, CancellationToken token)
```
Thank you!
