### ISSUE TITLE
NullReferenceException, seems to be storing no value for bool?

### ISSUE THREAD

**Issue by jimmycartrette** [ZiggyCreatures/FusionCache#323]
I'm just getting started with plugging FusionCache to replace our existing cache systems. I'm calling this:
_cache.Set(GetKeyName(key), obj, expiresIn);
With obj being a bool.
When it's brought back:
var maybeValue = _cache.TryGet<T>(GetKeyName(key));
Of type bool, I get a nullreferenceexception. 
```
System.Exception: Error in Evaluate_ExpiredSecretPasswordChangeMessage: System.NullReferenceException: Object reference not set to an instance of an object.
   at ZiggyCreatures.Caching.Fusion.Internals.Memory.FusionCacheMemoryEntry`1.GetValue[TValue1]() in D:\repos\FusionCache\src\ZiggyCreatures.FusionCache\Internals\Memory\FusionCacheMemoryEntry.cs:line 66
   at ZiggyCreatures.Caching.Fusion.FusionCache.GetValueFromMemoryEntry[TValue](String operationId, String key, IFusionCacheMemoryEntry entry, FusionCacheEntryOptions options) in D:\repos\FusionCache\src\ZiggyCreatures.FusionCache\FusionCache.cs:line 967
   at ZiggyCreatures.Caching.Fusion.FusionCache.TryGet[TValue](String key, FusionCacheEntryOptions options, CancellationToken token) in D:\repos\FusionCache\src\ZiggyCreatures.FusionCache\FusionCache_Sync.cs:line 565
```

Trying to dig into the cache itself, it has no "v" or value:

>hgetall v0:Fusion:fe08c382-ef5d-4fce-87f5-670b32d0770a:SecretMessage_Enabled
1) "absexp"
2) "638656609480003673"
3) "data"
4) "{\"m\":{\"e\":\"2024-10-27T21:22:28.0003673+00:00\"},\"t\":638656573480003673}"
5) "sldexp"
6) "-1"

A good entry looks like this:
1) "absexp"
2) "638656608619653733"
3) "data"
4) "{\"v\":true,\"m\":{\"e\":\"2024-10-27T21:21:01.9653733+00:00\"},\"t\":638656572619653733}"
5) "sldexp"
6) "-1"

Any idea what could be going wrong? Using newtonsoft serializer, redis backplane/L2

**Comment by jimmycartrette** [comment]
I think the default JsonSerializerSettings needs DefaultValueHandling to be set:
```
                var serializer = new FusionCacheNewtonsoftJsonSerializer(new JsonSerializerSettings()
                {
                    TypeNameHandling = TypeNameHandling.Auto,
                    DefaultValueHandling = DefaultValueHandling.Populate
                });
```

**Comment by jodydonetti** [comment]
Hi @jimmycartrette , yes I was about to suggest looking into the configuration of the specific serializer.
Glad it now works.

Just ot be clear, the code above was `var maybeValue = _cache.TryGet<bool>(GetKeyName(key));` (`bool`) or `var maybeValue = _cache.TryGet<bool?>(GetKeyName(key));` (`bool?`) ?

I want to doublecheck something...

**Comment by jimmycartrette** [comment]
The first one, not a nullable value type

**Comment by jodydonetti** [comment]
What I thought: I don't if this is exactly the case, but in general if you try do deserialize `null` into a `bool` you will have an exception.

**Comment by jimmycartrette** [comment]
There might be a bit more to it, I had to modify EmitDefaultValue to true on Value in FusionCacheDistributedEntry to get it working.
```
[DataMember(Name = "v", EmitDefaultValue = true)]
public TValue Value { get; set; }
```

I'm not sure why setting DefaultDefaultValueHandling = DefaultValueHandling.Populate;

Didn't do it. And why others aren't see this. I'm on .net framework

**Comment by jodydonetti** [comment]
Mmmh, you being forced to change FusionCache source code is not something I'd consider ideal, more like a temporary mitigation.
I'd like to get to the bottom of this, just in case a fix is needed on FusionCache side, but to do that I need an [MRE](https://en.wikipedia.org/wiki/Minimal_reproducible_example), ideally a 10 line console app or something like that.
Would you please provide one so I can get to the bottom of it and if necessary fix it?
Thanks!
