### ISSUE TITLE
Cache keys prefix

### ISSUE THREAD

**Issue by sigurdhj** [ZiggyCreatures/FusionCache#80]
Hi.

I've noticed that all my keys are getting prefixed with v1. Why is this happening? Is it possible to remove the v1 prefix?

**Comment by jodydonetti** [comment]
Hi @sigurdhj and thanks for using FusionCache.

I suppose you are talking about the distributed cache, right? If that is the case that was done to be future proof for an eventual evolution of the distributed cache format.

Having said that you can configure the way cache keys are modified (or not) with the `FusionCacheOptions.DistributedCacheKeyModifierMode` option, where you can if you prefer `Prefix` (the default), `Suffix` or `None`, so setting it to `None` will not touch the cache keys at all.

Hope this helps.

**Comment by sigurdhj** [comment]
Thanks, that worked!
