### ISSUE TITLE
[BUG] Can't instantiate MemoryPack serializer on NET7

### ISSUE THREAD

**Issue by RMcD** [ZiggyCreatures/FusionCache#93]
**Describe the bug**
Trying to instantiate the FusionCacheCysharpMemoryPackSerializer on .NET7 throws a runtime exception.

```
Method 'Serialize' on type 'ZiggyCreatures.Caching.Fusion.Serialization.CysharpMemoryPack.Internals.FusionCacheDistributedEntryFormatter`1' from assembly 'ZiggyCreatures.FusionCache.Serialization.CysharpMemoryPack, Version=0.17.0.0, Culture=neutral, PublicKeyToken=null' tried to implicitly override a method with weaker type parameter constraints.
```

**To Reproduce**
Here's a [MRE (Minimal Reproducible Example)](https://en.wikipedia.org/wiki/Minimal_reproducible_example) of the issue:
```
// When using .NET7 runtime target.
var _ = new FusionCacheCysharpMemoryPackSerializer();
```

LinqPad
```
<Query Kind="Statements">
  <NuGetReference>ZiggyCreatures.FusionCache.Serialization.CysharpMemoryPack</NuGetReference>
  <Namespace>ZiggyCreatures.Caching.Fusion</Namespace>
  <Namespace>ZiggyCreatures.Caching.Fusion.Serialization</Namespace>
  <Namespace>ZiggyCreatures.Caching.Fusion.Serialization.CysharpMemoryPack</Namespace>
  <RuntimeVersion>7.0</RuntimeVersion>
</Query>

var _ = new FusionCacheCysharpMemoryPackSerializer();
```

**Expected behavior**
The serializer should instantiate the object like it does on .NET6/netstandard2.1

**Versions**
I've encountered this issue on:
- FusionCache 0.17
- .NET version 7
- OS version Window10

**Additional context**

**Comment by jodydonetti** [comment]
Hi @RMcD and thanks for using FusionCache.
Will check and let you know.

**Comment by jodydonetti** [comment]
I can confirm the same problem, and I think I know what is happening here: to be sure though, I have summon the MemoryPack creator.

I created [an issue](https://github.com/Cysharp/MemoryPack/issues/96) there, let's see what @neuecc willsay.

**Comment by jodydonetti** [comment]
Hi @RMcD , an update on this: my guess was in fact correct, and you can see the details of the discussion in the issue I linked.

Long story short: I don't know what will happen regarding MemoryPack itself, if it will make some changes to have a more standard experience regarding transitive .NET version dependencies or not. In the meantime though, I tried a different approach for my library (thanks to some suggestions from its author, which is super kind and helpful 🙏) and after some tweaks I made it to work well, and all the 300+ tests are now passing.
So now I'm preparing a new version which should fix this specific issue: I will release it soon, but I don't know if I will be able to do it today or later. Will update you.

Oh, and thanks for your tip, which started the conversation!

**Comment by jodydonetti** [comment]
FYI: I just pushed the [new branch](https://github.com/ZiggyCreatures/FusionCache/tree/feature/net7_with_memorypack)

**Comment by jodydonetti** [comment]
Hi @RMcD , just wanted to update you: the code has been updated and it's now working correctly also on .NET 7, and thanks to some back & forth with MemoryPack author it's now in perfect shape, and I'll release a new version very soon.

**Comment by jodydonetti** [comment]
Hi @RMcD , the new [v0.18.0](https://github.com/ZiggyCreatures/FusionCache/releases/tag/v0.18.0) has been released 🎉

It includes the needed changes, too.

Please let me know if everything is fine.
