### ISSUE TITLE
[FEATURE] Plugin Improvements

### ISSUE THREAD

**Issue by aKzenT** [ZiggyCreatures/FusionCache#98]
While writing a plugin for FusionCache, I noticed some things that made it harder than necessary and could be improved. I managed to work arround these limitations, but I want to share my experience as they might be interesting to improve the functionality for future versions.

Suggestions:
1. **Allow access to internal memory cache and distributed cache instances**: The API surface for plugins is exactly the same as the public API. While I understand the benefits of hiding implementation details, I think it would be useful to allow plugins to get more access to the internal workings of FusionCache as they are intented to extend this functionality. Plugin authors can also be expected to have more knowledge of this internal workings and understand that they can break things.
2. **Enrich information in events**: In many key events you only get the "Key" in the event data. Plugins might be interested however in knowing the entry options or other information that was used. 
3. **Provide more events**: Specifically in addition to Hit and Miss events on the distributed cache that happen after retrieving data, I was missing a simple "Get" event that is raised just before the distributed cache is being hit.
4. **Provide "Hooks"**: Events give you a read-only access to the operations that are happening. For more advanced scenarios you often need a way to intercept and change things.
5. **Allow custom backplane messages**: Instead of having a fixed set of possible operations and a "CacheKey" argument allow plugins to define their own messages so plugin instances can communicate between nodes.
6. **Provide custom extension data**: Both the cache itself and the cache entry options would benefit from a dictionary-like extension-data property that can be used by plugins. Assuming the entry-options are part of the event data in the future, this provides a way for users to configure options for an entry that are specific for a plugin. Instead of directly manipulation the dictionary, users would use extension methods on the entry-option object to configure plugin specific data.
7. **Provide a list of registered plugins on the cache API**: It is currently only possible to add/remove plugins, but not to enumerate them. This makes it hard to provide an extension method on a FusionCache instances, that utilizes a plugin instance of this cache. So for example, imagine I wrote a plugin to "flush the cache", it would be nice to be able to provide a "Flush" extension method on IFusionCache that finds the plugin in the cache and invokes its functionality.

The little painpoints aside, the library is really great work. Thank you very much!

**Comment by jodydonetti** [comment]
Wow @aKzenT , thanks for taking the time to articulate your experience and needs so deeply! I can't stress how much I appreciate it.

Will get back to you with some thoughts for each point soon.

**Comment by jodydonetti** [comment]
After some time (a lot, actually) and after v1 went out, I still feel like opening up too much about the internals of FusionCache would be too risky from an evolution perspective, so I'm closing this.
